/* Generated By:JavaCC: Do not edit this line. GramaticaConstants.java */
package lab03;


/** 
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface GramaticaConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int NUM = 5;
  /** RegularExpression Id. */
  int VAR = 6;
  /** RegularExpression Id. */
  int IMPRIMIR = 7;
  /** RegularExpression Id. */
  int ID = 8;
  /** RegularExpression Id. */
  int PCOMA = 9;
  /** RegularExpression Id. */
  int PARENI = 10;
  /** RegularExpression Id. */
  int PAREND = 11;
  /** RegularExpression Id. */
  int MAS = 12;
  /** RegularExpression Id. */
  int MENOS = 13;
  /** RegularExpression Id. */
  int POR = 14;
  /** RegularExpression Id. */
  int DIV = 15;
  /** RegularExpression Id. */
  int EQ = 16;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\r\"",
    "\"\\n\"",
    "<NUM>",
    "\"var\"",
    "\"imprimir\"",
    "<ID>",
    "\";\"",
    "\"(\"",
    "\")\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"=\"",
  };

}
