/* Generated By:JavaCC: Do not edit this line. GramaticaConstants.java */
package lab03;


/** 
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface GramaticaConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int NUM = 5;
  /** RegularExpression Id. */
  int VAR = 6;
  /** RegularExpression Id. */
  int IMPRIMIR = 7;
  /** RegularExpression Id. */
  int BREAK = 8;
  /** RegularExpression Id. */
  int CONTINUE = 9;
  /** RegularExpression Id. */
  int IF = 10;
  /** RegularExpression Id. */
  int ELSE = 11;
  /** RegularExpression Id. */
  int WHILE = 12;
  /** RegularExpression Id. */
  int ID = 13;
  /** RegularExpression Id. */
  int PCOMA = 14;
  /** RegularExpression Id. */
  int PARENI = 15;
  /** RegularExpression Id. */
  int PAREND = 16;
  /** RegularExpression Id. */
  int LLAVEI = 17;
  /** RegularExpression Id. */
  int LLAVED = 18;
  /** RegularExpression Id. */
  int MAS = 19;
  /** RegularExpression Id. */
  int MENOS = 20;
  /** RegularExpression Id. */
  int POR = 21;
  /** RegularExpression Id. */
  int DIV = 22;
  /** RegularExpression Id. */
  int GT = 23;
  /** RegularExpression Id. */
  int LT = 24;
  /** RegularExpression Id. */
  int EQ = 25;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\r\"",
    "\"\\n\"",
    "<NUM>",
    "\"var\"",
    "\"imprimir\"",
    "\"break\"",
    "\"continue\"",
    "\"if\"",
    "\"else\"",
    "\"while\"",
    "<ID>",
    "\";\"",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\">\"",
    "\"<\"",
    "\"=\"",
  };

}
